kind: pipeline
type: docker
name: build

platform:
  os: linux
  arch: arm

steps:
  - name: build
    image: plugins/docker
    settings:
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      registry: registry.itdog.me
      repo: registry.itdog.me/hko_bot
      tags:
        - latest
        - ${DRONE_COMMIT}

trigger:
  branch:
    - master
